"""Trace every live-run number in the manuscript back to a committed artifact.

The manuscript's integrity rule is that no value is hand-written: each one
must be reproducible from the recorded output of a real run. This script
enforces that for the numbers Sections VI-G and VI-H quote from the
managed-runtime anchor, the load contrast, and probe conditions C3/C4.

It checks two things per value, because either alone is insufficient:
  1. the exact rounded string appears in the .tex, and
  2. it rounds correctly from the artifact it claims to come from.

A value that has drifted, or an artifact regenerated by a re-run, fails
here rather than in review.

Usage:
    python scripts/verify_manuscript_numbers.py path/to/main.tex
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def _load(rel):
    p = ROOT / rel
    if not p.exists():
        sys.exit(f"missing artifact {rel} - run the live harness first; "
                 "this script never invents numbers.")
    return json.loads(p.read_text())


def main(argv=None) -> int:
    argv = argv or sys.argv[1:]
    if not argv:
        sys.exit(__doc__.strip().splitlines()[-1])
    tex = Path(argv[0]).read_text()

    ac = _load("anchor/results/anchor_findings_agentcore.json")
    c3 = _load("anchor/p7/results/C3/summary.json")
    c4 = _load("anchor/p7/results/C4/summary.json")
    cw = _load("anchor/p7/results/cloudwatch_corroboration.json")

    a1 = ac["by_concurrency"]["agentcore"]["c1"]
    a8 = ac["by_concurrency"]["agentcore"]["c8"]
    bd = ac["by_concurrency"]["bedrock_direct_use1"]["c1"]
    ov1 = a1["p1_median_latency_s"] - a1["p1_median_in_runtime_latency_s"]
    ov2 = a1["p2_median_latency_s"] - a1["p2_median_in_runtime_latency_s"]

    # (label, exact string that must appear in the .tex, artifact value)
    cases = [
        ("AgentCore P1 c=1", "2.03~s", a1["p1_median_latency_s"]),
        ("AgentCore P2 c=1", "1.06~s", a1["p2_median_latency_s"]),
        ("AgentCore P1 c=8", "6.87~s", a8["p1_median_latency_s"]),
        ("AgentCore P2 c=8", "3.60~s", a8["p2_median_latency_s"]),
        ("direct us-east-1 P1", "1.65~s", bd["p1_median_latency_s"]),
        ("direct us-east-1 P2", "0.58~s", bd["p2_median_latency_s"]),
        ("in-runtime P1 c=1", "1.54~s", a1["p1_median_in_runtime_latency_s"]),
        ("in-runtime P2 c=1", "0.59~s", a1["p2_median_in_runtime_latency_s"]),
        ("in-runtime P1 c=8", "1.68~s", a8["p1_median_in_runtime_latency_s"]),
        ("in-runtime P2 c=8", "0.56~s", a8["p2_median_in_runtime_latency_s"]),
        ("managed-runtime overhead P1", "0.50~s", ov1),
        ("managed-runtime overhead P2", "0.47~s", ov2),
    ]
    ratios = [
        ("AgentCore ratio c=1", r"$1.91\times$", a1["latency_ratio_p1_over_p2"]),
        ("AgentCore ratio c=8", r"$1.91\times$", a8["latency_ratio_p1_over_p2"]),
        ("direct ratio", r"$2.86\times$", bd["latency_ratio_p1_over_p2"]),
    ]
    counts = [
        ("c=8 P1 completions", "89", a8["p1_n_ok"]),
        ("C3 wire attempts", 60, c3["wire_attempts_total"]),
        ("C4 wire attempts", 60, c4["wire_attempts_total"]),
        ("C3 duplicate executions", 30, c3["duplicate_agent_executions"]),
        ("C4 duplicate executions", 0, c4["duplicate_agent_executions"]),
        ("C3 executions (CloudWatch)", 60,
         cw["per_condition"]["C3"]["executions_total"]),
        ("C4 executions (CloudWatch)", 30,
         cw["per_condition"]["C4"]["executions_total"]),
    ]

    bad = []
    for label, s, val in cases:
        shown = float(s.replace("~s", ""))
        if s not in tex:
            bad.append(f"{label}: '{s}' not present in manuscript")
        elif abs(shown - val) > 0.006:
            bad.append(f"{label}: manuscript says {shown}, artifact has {val}")
    for label, s, val in ratios:
        shown = float(s.split("$")[1].replace(r"\times", ""))
        if s not in tex:
            bad.append(f"{label}: '{s}' not present in manuscript")
        elif abs(shown - val) > 0.005:
            bad.append(f"{label}: manuscript says {shown}, artifact has {val}")
    # Counts are asserted against the artifacts directly: the bare integers
    # are too common in prose for a substring test to mean anything.
    for label, expected, val in counts:
        if str(expected) != str(val):
            bad.append(f"{label}: expected {expected}, artifact has {val}")

    # C3/C4 attribution precondition: if the CRM side redelivered anything,
    # a duplicate execution cannot be attributed to the AWS direction.
    for lbl, s in (("C3", c3), ("C4", c4)):
        if s["redeliveries_observed"] != 0 or s["deliveries_observed"] != s["published"]:
            bad.append(f"{lbl}: CRM-side redelivery present; the "
                       f"attribution the manuscript claims does not hold")

    n = len(cases) + len(ratios) + len(counts)
    if bad:
        print(f"verify_manuscript_numbers: {len(bad)} PROBLEM(S)")
        for b in bad:
            print("  -", b)
        return 1
    print(f"verify_manuscript_numbers: OK ({n} values traced to committed "
          f"artifacts; C3/C4 attribution precondition holds)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
